# Site settings
title: Developer's Diary
email: kedar.krishnan@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A diary of a software developer as he sails through the vast sea of knowledge of ever changing technologies. 
  Passionate to learn he writes his learnings down to discover more and more.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://kedarkrishnan.github.io" # the base hostname & protocol for your site
twitter_username: kedarkrishnan
github_username:  kedarkrishnan

# Build settings
markdown: kramdown

gems: 
- jekyll-sitemap

sass:
  style: compressed
